from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class ProviderHealthState(str, Enum):
    AVAILABLE = "AVAILABLE"
    DEGRADED = "DEGRADED"
    RATE_LIMITED = "RATE_LIMITED"
    QUOTA_EXCEEDED = "QUOTA_EXCEEDED"
    AUTH_FAILED = "AUTH_FAILED"
    UNAVAILABLE = "UNAVAILABLE"
    DISABLED = "DISABLED"


class ProviderMetadata(BaseModel):
    """Execution telemetry and health status of the explanation provider."""
    provider: str = Field(..., description="gemini, groq, openai, or deterministic")
    provider_status: ProviderHealthState
    fallback_used: bool = False
    fallback_reason: Optional[str] = None
    model: Optional[str] = None
    request_timestamp: str
    latency_ms: float = 0.0


class NarrativeExplanation(BaseModel):
    """Structured, evidence-grounded natural language explanation generated by LLM or deterministic engine."""
    executive_summary: str
    operational_context: str
    key_tradeoffs: List[str] = Field(default_factory=list)
    risk_mitigation: str
    recommendations: List[str] = Field(default_factory=list)


class FeatureContribution(BaseModel):
    """Feature-level attribution record from SHAP or model surrogate."""
    feature: str
    input_value: float
    contribution: float
    direction: str = Field(..., description="POSITIVE or NEGATIVE contribution")
    importance_rank: int = Field(..., ge=1)


class AspectExplanation(BaseModel):
    """Explainability grouped by domain aspect."""
    aspect: str = Field(..., description="maintenance_duration, asset_risk_priority, or operational_impact")
    summary: str
    features: List[FeatureContribution] = Field(default_factory=list)


class PredictionExplanationResponse(BaseModel):
    """Model-level explainability for a single maintenance request."""
    request_id: str
    predicted_score: float
    predicted_category: str
    explanation_method: str = Field(default="SHAP", description="SHAP, TREE_CONTRIBUTIONS, or SURROGATE_FALLBACK")
    base_value: float = 0.0
    aspects: Dict[str, AspectExplanation] = Field(default_factory=dict)
    feature_contributions: List[FeatureContribution] = Field(default_factory=list)


class DecisionTraceStage(BaseModel):
    """One discrete phase in the deterministic decision pipeline."""
    stage_name: str = Field(..., description="INPUT, ML_PREDICTION, CONSTRAINT_CHECK, CANDIDATE_WINDOW, CONFLICT_CHECK, OPTIMIZATION, SCORE, or FINAL_DECISION")
    status: str = Field(..., description="PASSED, FAILED, FEASIBLE, SCHEDULED, DEFERRED, etc.")
    details: Dict[str, Any] = Field(default_factory=dict)


class RequestDecisionTrace(BaseModel):
    """End-to-end decision lineage trace for a specific maintenance request."""
    request_id: str
    final_decision: str = Field(..., description="SELECTED, POSTPONED, or REJECTED")
    stages: List[DecisionTraceStage] = Field(default_factory=list)


class ConstraintExplanationRecord(BaseModel):
    """Operational validation detail derived from actual RailwayConstraintEngine check."""
    constraint_type: str
    canonical_type: str
    passed: bool
    request_id: Optional[str] = None
    block_id: Optional[str] = None
    affected_window: Optional[List[int]] = None
    reason: str
    relevant_values: Dict[str, Any] = Field(default_factory=dict)


class OptimizerCandidateEvidence(BaseModel):
    """Evidence metrics for an evaluated candidate strategy."""
    strategy_name: str
    is_feasible: bool
    score: float
    hard_violations_count: int
    objective_contribution: float = 0.0
    grouping_benefit: float = 0.0
    operational_impact: float = 0.0
    asset_priority_benefit: float = 0.0
    overdue_benefit: float = 0.0
    is_selected: bool = False


class OptimizerExplanation(BaseModel):
    """Evidence and metrics explaining optimizer strategy selection."""
    selected_strategy: str
    candidates_evaluated: List[OptimizerCandidateEvidence] = Field(default_factory=list)
    replanning_applied: bool = False
    decision_log: List[Dict[str, Any]] = Field(default_factory=list)


class ScoreBreakdown(BaseModel):
    """Unified decomposition of the composite quality score."""
    overall_score: float
    asset_availability: float = 0.0
    risk_coverage: float = 0.0
    overdue: float = 0.0
    operational_impact: float = 0.0
    train_conflict: float = 0.0
    grouping: float = 0.0
    resource_utilization: float = 0.0
    factor_scores: Dict[str, float] = Field(default_factory=dict)


class DecisionReasonRecord(BaseModel):
    """Structured evidence-based justification for a specific block scheduling state."""
    request_id: str
    decision: str = Field(..., description="SELECTED, POSTPONED, UNSCHEDULED, GROUPED, or ALTERNATIVE_WINDOW")
    primary_reason: str
    evidence: List[str] = Field(default_factory=list)
    slot: Optional[List[int]] = None
    affected_asset: Optional[str] = None


class UnifiedPlanExplanation(BaseModel):
    """Unified explainability schema across backend, frontend, audit, and future agents."""
    planning_run_id: str
    selected_plan: Dict[str, Any]
    prediction_evidence: Dict[str, PredictionExplanationResponse] = Field(default_factory=dict)
    decision_trace: List[RequestDecisionTrace] = Field(default_factory=list)
    constraint_results: List[ConstraintExplanationRecord] = Field(default_factory=list)
    optimizer_decisions: OptimizerExplanation
    score_breakdown: ScoreBreakdown
    scheduled_reasons: List[DecisionReasonRecord] = Field(default_factory=list)
    postponed_reasons: List[DecisionReasonRecord] = Field(default_factory=list)
    grouping_reasons: List[DecisionReasonRecord] = Field(default_factory=list)
    alternative_reasons: List[DecisionReasonRecord] = Field(default_factory=list)
    warnings: List[str] = Field(default_factory=list)
    model_versions: Dict[str, str] = Field(default_factory=dict)
    provider_metadata: Optional[ProviderMetadata] = None
    narrative: Optional[NarrativeExplanation] = None
